# Generated by Django 2.1.7 on 2019-04-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190406_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
